export const EXTENSION_ID = 'mitraHelix';
export const VIEW_ID = 'mitraHelix.chatView';
export const COMMAND_NEW_CHAT = 'mitraHelix.newChat';
export const COMMAND_FOCUS_CHAT = 'mitraHelix.focusChat';
export const OUTPUT_CHANNEL_NAME = 'MitraHelix';
export const MAX_ITERATIONS = 50;
export const MAX_FILE_SIZE = 100_000;
export const MAX_COMMAND_OUTPUT = 50_000;
export const MAX_SEARCH_RESULTS = 100;
export const DEFAULT_COMMAND_TIMEOUT = 120_000;
export const MAX_CONTENT_PREVIEW = 50_000;
export const DEFAULT_MAX_OUTPUT_TOKENS = 16384;
export const DEFAULT_MAX_BUDGET = 1.0;
export const DEFAULT_OLLAMA_BASE_URL = 'http://localhost:11434';
export const MAX_DIAGNOSTICS = 50;

export const PLACEHOLDER_DIAGNOSTICS = '[Diagnostics included in context]';
export const PLACEHOLDER_TERMINAL = '[Terminal output included in context]';
export const PLACEHOLDER_SELECTION = '[Editor selection included in context]';
